---

ci:
  autoupdate_schedule: monthly

default_stages:
- commit
exclude: docs|migrations|.git|.tox|deploy|bin
fail_fast: false

repos:
- hooks:
  - id: check-toml
  - id: check-vcs-permalinks
  - exclude: "/templates/"
    id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0

- hooks:
  - id: ansible-lint
  repo: https://github.com/ansible/ansible-lint
  rev: v24.2.0
