name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Lint the project
      uses: pre-commit/action@v3.0.1

  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Ansible
      run: pip install ansible
    - name: Install Ansible collections
      run: ansible-galaxy collection install -r requirements.yml
    - name: Playbook syntax check
      run: ansible-playbook --syntax-check -i inventories/his_servers plays/install_dhis2.yml